export const STATUS = {
        MISSING: "MISSING",
        MISSING_URGENT: "MISSING_URGENT",
        APPROVED: "APPROVED",
        PRICE_UPDATED: "PRICE_UPDATED",
        QUANTITY_UPDATED: "QUANTITY_UPDATED",
        QUANTITY_AND_PRICE_UPDATED: "QUANTITY_AND_PRICE_UPDATED"
      }